version: '3.8'
volumes:
  rethinkdb-data:
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
  db:
    image: rethinkdb:2.4-bookworm-slim
    restart: unless-stopped
    volumes:
      - rethinkdb-data:/data
    ports:
      - "8080:8080"
